trigger: none

pool:
  name: Default
  demands:
    - agent.name -equals self-hosted-agent-name # Replace with your actual self-hosted agent name

parameters:
  - name: deploy
    displayName: Deploy
    type: string
    default: "resource-groups" # Set a default value here
    values:
      - resource-groups
      - base
      - piwind
      - models
      - azure
      - oasis
      - images

resources:
  repositories:
    - repository: OasisPlatform
      name: OasisLMF/OasisPlatform
      endpoint: OasisLMF
      type: github
      ref: main
    - repository: OasisPiWind
      name: OasisLMF/OasisPiWind
      endpoint: OasisLMF
      type: github
      ref: main

steps:
  - checkout: self
    path: OasisAzureDeployment
  - checkout: OasisPlatform
    path: OasisPlatform
  - checkout: OasisPiWind
    path: OasisPiWind

  - task: AzureCLI@2
    displayName: Deploy
    inputs:
      azureSubscription: "Azure connection"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -e
        cd ./OasisAzureDeployment
        OE_SETTINGS_FILE=settings/settings.sh ./deploy.sh ${{ parameters.deploy }}
